plugin:
    name: 'eliseontwerpt.websitecollection::lang.plugin.name'
    description: 'eliseontwerpt.websitecollection::lang.plugin.description'
    author: EliseOntwerpt
    icon: oc-icon-external-link-square
    homepage: ''
navigation:
    main-menu-item:
        label: 'eliseontwerpt.websitecollection::lang.plugin.name'
        url: eliseontwerpt/websitecollection/websites
        icon: icon-external-link-square
