list: $/eliseontwerpt/websitecollection/models/websites/columns.yaml
modelClass: Eliseontwerpt\WebsiteCollection\Models\Websites
title: Websites
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eliseontwerpt/websitecollection/websites/update/:id'
